"""v2.5 S4 markdown memory layer.

Filesystem layout under DATA_ROOT/memory/:

    TASTE.md        Generated by consolidate_taste(). Reflects engagement
                    history + persisted taste anchors. Regenerated on each
                    write -- human edits are overwritten. Edit USER.md for
                    free-form notes the consolidator must preserve.

    USER.md         Free-form, user-edited. Never overwritten by the
                    consolidator. Has a recommended H2 skeleton on first
                    write; thereafter it is treated as opaque markdown.

Anchors -- the user's explicit "I like X / avoid Y" preferences -- live in
the existing v2.5 ``memory_layer`` SQLite table (created by migration
0006). Keys are namespaced under ``taste.`` so future sub-systems can
share the table cleanly:

    taste.preferred_hooks      bullet list, one item per line
    taste.preferred_formats    bullet list
    taste.avoid                bullet list

The Obsidian mirror is opt-in: when ``settings.obsidian_vault_path`` is
set, every write also lands a copy at <vault>/Uoink/. Failure to write
the mirror does NOT fail the primary write -- it is logged and surfaced
in the response so the user can fix the path without losing data.

This module owns NO transport. server.py wraps it with HTTP handlers;
uoink_mcp_tools.py wraps it with MCP tools. Both transports route
through the public functions below."""

from __future__ import annotations

import json
import logging
import os
from datetime import datetime
from pathlib import Path
from typing import Any

log = logging.getLogger("uoink.memory_layer")

# The 3 anchor sections an agent can edit via update_user_taste(section, ...).
# Listed as the canonical keys (sans the ``taste.`` prefix) -- the section
# parameter is validated against this set to avoid silent typos populating
# new rows the consolidator will never read.
ANCHOR_SECTIONS = ("preferred_hooks", "preferred_formats", "avoid")

# USER.md skeleton -- written only when USER.md is missing. After first
# write the user owns the file and we never rewrite it.
_USER_MD_SKELETON = """# User

Free-form notes the consolidator preserves. Edit anything below.

## Channels I admire

- (add channels you study or want to riff on)

## My channel(s)

- (populated by P3 your-channel mode once verified)

## Topics

- (areas you want Uoink to bias toward in suggestions)

## Workflow notes

- (your own process notes, hand-edited)
"""


# ---- paths (computed lazily so DATA_ROOT can be monkeypatched in tests) ----
def memory_root(data_root: Path) -> Path:
    p = Path(data_root) / "memory"
    p.mkdir(parents=True, exist_ok=True)
    return p


def taste_path(data_root: Path) -> Path:
    return memory_root(data_root) / "TASTE.md"


def user_path(data_root: Path) -> Path:
    return memory_root(data_root) / "USER.md"


# ---- anchor read/write (memory_layer SQLite table) ------------------------
def _now_iso() -> str:
    return datetime.utcnow().replace(microsecond=0).isoformat() + "Z"


def get_anchor(idx, section: str) -> str:
    """Return the persisted anchor body for one section, or ''."""
    key = f"taste.{section}"
    row = idx._conn.execute(
        "SELECT value FROM memory_layer WHERE key=?", (key,)).fetchone()
    return (row["value"] if row else "") or ""


def set_anchor(idx, section: str, content: str) -> None:
    """Upsert one anchor. Trims trailing whitespace + collapses CRLF to LF so
    the consolidator can stitch sections without surprise blank-line drift."""
    if section not in ANCHOR_SECTIONS:
        raise ValueError(
            f"section must be one of {ANCHOR_SECTIONS}, got {section!r}")
    key = f"taste.{section}"
    body = (content or "").replace("\r\n", "\n").rstrip() + "\n"
    with idx._lock:
        idx._conn.execute(
            "INSERT INTO memory_layer (key, value, updated_at) VALUES (?,?,?) "
            "ON CONFLICT(key) DO UPDATE SET value=excluded.value, "
            "updated_at=excluded.updated_at",
            (key, body, _now_iso()))


# ---- consolidation --------------------------------------------------------
def consolidate_taste(idx, *, top_n: int = 10) -> str:
    """Pure function: produce the TASTE.md content from current engagement
    events + persisted anchors. Idempotent -- same inputs -> same string. No
    file I/O.

    Performance anchors are the top-N videos by value_score. They get
    rendered with the video_id only (no title lookup here -- the dashboard
    can join when it renders, this keeps the memory layer dependency-light).
    """
    out: list[str] = []
    out.append("# Taste")
    out.append("")
    out.append("_Generated by Uoink `consolidate_taste()`. "
                "Edit `USER.md` for free-form notes -- this file is "
                "regenerated whenever an anchor is updated or "
                "`/memory/taste` is POSTed, and any human edits here will "
                "be overwritten._")
    out.append("")

    for label, key in (("Preferred hooks", "preferred_hooks"),
                        ("Preferred formats", "preferred_formats"),
                        ("Avoid", "avoid")):
        out.append(f"## {label}")
        out.append("")
        body = get_anchor(idx, key).strip()
        out.append(body if body else "_no anchors yet_")
        out.append("")

    out.append("## Performance anchors")
    out.append("")
    out.append("_Top videos by `value_score` (v2.5 S2 -- weighted, "
                "30-day half-life decay)._")
    out.append("")
    try:
        top = idx.top_engaged(limit=top_n)
    except Exception as e:
        log.warning("top_engaged failed during consolidate: %s", e)
        top = []
    if not top:
        out.append("_no engagement yet_")
    else:
        for s in top:
            out.append(f"- `{s['video_id']}` -- value_score "
                        f"{s['value_score']:.2f}, {s['total_events']} events")
    out.append("")

    out.append(f"## Last consolidated")
    out.append("")
    out.append(_now_iso())
    out.append("")
    return "\n".join(out)


# ---- file write/read ------------------------------------------------------
def _atomic_write(path: Path, content: str) -> None:
    """Write text atomically: tmp file -> os.replace. Avoids torn writes if
    the helper is killed mid-write."""
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(content, encoding="utf-8", newline="\n")
    os.replace(str(tmp), str(path))


def _maybe_mirror(name: str, content: str, *, vault_path: str | None) -> dict:
    """Best-effort Obsidian mirror. Returns {ok, path?, error?}."""
    if not vault_path:
        return {"ok": True, "path": None}
    try:
        target = Path(vault_path) / "Uoink"
        target.mkdir(parents=True, exist_ok=True)
        dst = target / name
        _atomic_write(dst, content)
        return {"ok": True, "path": str(dst)}
    except Exception as e:
        log.warning("vault mirror failed for %s: %s", name, e)
        return {"ok": False, "error": str(e)}


def write_taste(idx, data_root: Path, *,
                vault_path: str | None = None) -> dict:
    """Consolidate + write TASTE.md (+ mirror). Returns metadata dict."""
    content = consolidate_taste(idx)
    path = taste_path(data_root)
    _atomic_write(path, content)
    mirror = _maybe_mirror("TASTE.md", content, vault_path=vault_path)
    return {"ok": True, "path": str(path), "bytes": len(content),
            "mirror": mirror, "last_consolidated": _now_iso()}


def read_taste(idx, data_root: Path, *,
                vault_path: str | None = None,
                consolidate_if_missing: bool = True) -> dict:
    """Read TASTE.md. If absent and ``consolidate_if_missing``, regenerate
    it on the fly so first-call from an agent never returns an error."""
    path = taste_path(data_root)
    if not path.exists() and consolidate_if_missing:
        write_taste(idx, data_root, vault_path=vault_path)
    if not path.exists():
        return {"ok": True, "content": "", "path": str(path)}
    return {"ok": True, "content": path.read_text(encoding="utf-8"),
            "path": str(path)}


def read_user(data_root: Path) -> dict:
    """Read USER.md. Writes the skeleton on first call so the user has a
    starting point to edit -- subsequent calls return whatever is on disk."""
    path = user_path(data_root)
    if not path.exists():
        _atomic_write(path, _USER_MD_SKELETON)
    return {"ok": True, "content": path.read_text(encoding="utf-8"),
            "path": str(path)}


def write_user(data_root: Path, content: str, *,
                vault_path: str | None = None) -> dict:
    """Replace USER.md verbatim. No schema validation -- USER.md is opaque
    markdown by design."""
    if not isinstance(content, str):
        raise ValueError("content must be a string")
    path = user_path(data_root)
    _atomic_write(path, content)
    mirror = _maybe_mirror("USER.md", content, vault_path=vault_path)
    return {"ok": True, "path": str(path), "bytes": len(content),
            "mirror": mirror}


def update_user_taste(idx, data_root: Path, section: str, content: str,
                       *, vault_path: str | None = None) -> dict:
    """Update one anchor section + re-consolidate TASTE.md."""
    set_anchor(idx, section, content)
    return write_taste(idx, data_root, vault_path=vault_path)
