-- v3 P4 Build Workspace -- per-video planning sessions.
--
-- A "workspace" is one act of planning a video: pick a format + topic +
-- hook target, let the helper assemble a relevant corpus slice (overperformer
-- yoinks ranked by S1 facets + S2 engagement value_score + optional S4 taste
-- anchors), then iterate on a draft with critique-against-corpus runs.
--
-- This PR introduces the storage shape. The compute is model-agnostic (the
-- calling agent does the LLM work via MCP; BYO key on-server is fallback)
-- so the helper just persists structure -- the critique log is a JSONL
-- of critique calls + findings + outputs.
--
-- Cascade: deleting a workspace drops its critique_log rows via FK.

CREATE TABLE IF NOT EXISTS workspaces (
    id             TEXT PRIMARY KEY,            -- ws_<8-hex> generated by helper
    created_at     TEXT NOT NULL,
    updated_at     TEXT NOT NULL,
    format         TEXT,                         -- S1 facet (one of FORMAT_ENUM) or NULL
    topic          TEXT,                         -- free-form topic string
    hook_target    TEXT,                         -- hook type the user is aiming for
    your_channel   TEXT,                         -- @handle / channel id; NULL = generic mode
    n_examples     INTEGER NOT NULL DEFAULT 10,
    assembled_yoinks TEXT NOT NULL DEFAULT '[]', -- JSON array of video_ids
    notes          TEXT                          -- free-form user notes
);
CREATE INDEX IF NOT EXISTS idx_workspaces_created ON workspaces(created_at);

CREATE TABLE IF NOT EXISTS workspace_critique_log (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    workspace_id TEXT NOT NULL,
    ts_utc       TEXT NOT NULL,
    mode         TEXT NOT NULL,    -- agent | byo_key (which compute path produced this)
    draft_text   TEXT NOT NULL,
    findings     TEXT,             -- JSON object with hook_strength, structural_deviation,
                                   -- pacing_issues, missing_audience_hooks (per ROADMAP P4)
    FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_workspace_critique_workspace
    ON workspace_critique_log(workspace_id);
CREATE INDEX IF NOT EXISTS idx_workspace_critique_ts
    ON workspace_critique_log(ts_utc);
